apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-yaml
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yyyujini/eks-cicd.git
    targetRevision: HEAD
    path: kustomize/overlays

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground