installCRD: true

controller:
  replicas: 1
  nodeSelector: { role : builders}

repoServer:
  replicas: 1
  nodeSelector: { role : builders}
dex:
  nodeSelector: { role : builders}
server:
  replicas: 1
  nodeSelector: { role : builders}
  service:
    type: NodePort
    namedTargetPort: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/tags: Environment=dev,Name=argocd-alb
      alb.ingress.kubernetes.io/subnets: subnet-, subnet-
  extraArgs:
    - --insecure
  config:
#    url: http://127.0.0.1:30080
    accounts.admin: apiKey, login
    repositories: |
     - url: https://github.com/yyyujini/eks-cicd.git
#    dex.config: |
#      connectors:
#        - type: github
#          id: github
#          name: GitHub
#          config:
#            clientID: xxx
#            clientSecret: xxx
#            orgs:
#            - name: xxx

  rbacConfig:
    policy.default: role:readonly
#    policy.csv: |
#      p, role:org-admin, applications, *, */*, allow
#      p, role:org-admin, clusters, get, *, allow
#      p, role:org-admin, repositories, get, *, allow
#      p, role:org-admin, repositories, create, *, allow
#      p, role:org-admin, repositories, update, *, allow
#      p, role:org-admin, repositories, delete, *, allow
#      g, xxx:devops, role:org-admin

redis:
  enabled: true
  nodeSelector: { role : builders }

redis-ha:
  enabled: false